### ISSUE TITLE
Error inflating class zendesk.messaging.ui.MessagingView

### ISSUE THREAD

**Issue by mopilo** [MrHou/zdplugin#1]
D/AndroidRuntime(16101): Shutting down VM
E/AndroidRuntime(16101): FATAL EXCEPTION: main
E/AndroidRuntime(16101): Process: com.suezElectric.suez, PID: 16101
E/AndroidRuntime(16101): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.suezElectric.suez/zendesk.messaging.MessagingActivity}: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class zendesk.messaging.ui.MessagingView
E/AndroidRuntime(16101):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
E/AndroidRuntime(16101):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
E/AndroidRuntime(16101):        at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(16101):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
E/AndroidRuntime(16101):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16101):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(16101):        at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime(16101):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16101):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(16101):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime(16101): Caused by: android.view.InflateException: Binary XML file line #2: Binary XML file line #2: Error inflating class zendesk.messaging.ui.MessagingView
E/AndroidRuntime(16101): Caused by: android.view.InflateException: Binary XML file line #2: Error inflating class zendesk.messaging.ui.MessagingView
E/AndroidRuntime(16101): Caused by: java.lang.reflect.InvocationTargetException
E/AndroidRuntime(16101):        at java.lang.reflect.Constructor.newInstance0(Native Method)
E/AndroidRuntime(16101):        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
E/AndroidRuntime(16101):        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
E/AndroidRuntime(16101):        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
E/AndroidRuntime(16101):        at zendesk.messaging.MessagingActivity.onCreate(MessagingActivity.java:121)
E/AndroidRuntime(16101):        at android.app.Activity.performCreate(Activity.java:7009)
E/AndroidRuntime(16101):        at android.app.Activity.performCreate(Activity.java:7000)
E/AndroidRuntime(16101):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
E/AndroidRuntime(16101):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
E/AndroidRuntime(16101):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
E/AndroidRuntime(16101):        at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(16101):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
E/AndroidRuntime(16101):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16101):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(16101):        at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime(16101):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16101):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(16101):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
E/AndroidRuntime(16101): Caused by: android.view.InflateException: Binary XML file line #13: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x7f040003 a=-1}
E/AndroidRuntime(16101): Caused by: java.lang.UnsupportedOperationException: Failed to resolve attribute at index 4: TypedValue{t=0x2/d=0x7f040003 a=-1}
E/AndroidRuntime(16101):        at android.content.res.TypedArray.getDimensionPixelSize(TypedArray.java:726)
E/AndroidRuntime(16101):        at android.view.ViewGroup$MarginLayoutParams.<init>(ViewGroup.java:7794)
E/AndroidRuntime(16101):        at android.widget.FrameLayout$LayoutParams.<init>(FrameLayout.java:439)
E/AndroidRuntime(16101):        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:370)
E/AndroidRuntime(16101):        at android.widget.FrameLayout.generateLayoutParams(FrameLayout.java:368)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:865)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.rInflate(LayoutInflater.java:866)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.inflate(LayoutInflater.java:489)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
E/AndroidRuntime(16101):        at zendesk.messaging.ui.MessagingView.<init>(MessagingView.java:48)
E/AndroidRuntime(16101):        at zendesk.messaging.ui.MessagingView.<init>(MessagingView.java:40)
E/AndroidRuntime(16101):        at java.lang.reflect.Constructor.newInstance0(Native Method)
E/AndroidRuntime(16101):        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
E/AndroidRuntime(16101):        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
E/AndroidRuntime(16101):        at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:555)
E/AndroidRuntime(16101):        at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:161)
E/AndroidRuntime(16101):        at zendesk.messaging.MessagingActivity.onCreate(MessagingActivity.java:121)
E/AndroidRuntime(16101):        at android.app.Activity.performCreate(Activity.java:7009)
E/AndroidRuntime(16101):        at android.app.Activity.performCreate(Activity.java:7000)
E/AndroidRuntime(16101):        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
E/AndroidRuntime(16101):        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
E/AndroidRuntime(16101):        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
E/AndroidRuntime(16101):        at android.app.ActivityThread.-wrap11(Unknown Source:0)
E/AndroidRuntime(16101):        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
E/AndroidRuntime(16101):        at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(16101):        at android.os.Looper.loop(Looper.java:164)
E/AndroidRuntime(16101):        at android.app.ActivityThread.main(ActivityThread.java:6494)
E/AndroidRuntime(16101):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(16101):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
E/AndroidRuntime(16101):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
D/OkHttp  (16101): <-- 200 https://widget-mediator.zopim.com/client/widget/account/status?embed_key=tFh19KFTd8BBqP3gihF65iF9ep7q4sLa (1216ms, 19-byte body)

**Comment by MuthuSubramaniam** [comment]
same issue for me too..

**Comment by mopilo** [comment]
I think I solved this buh can't remember how

**Comment by MuthuSubramaniam** [comment]
> I think I solved this buh can't remember how

NVM, i got it @mopilo  the issue is zendesk must give application style in manifeast.xml file

**Comment by mopilo** [comment]
> > I think I solved this buh can't remember how
> 
> NVM, i got it @mopilo the issue is zendesk must give application style in manifeast.xml file

ok cool. will close it then

**Comment by abdullahsonmez49** [comment]
Having the same problem, what will I do in manifest.xml?

**Comment by mopilo** [comment]
@abdullahsonmez49 check the example application. been a while can't remember what was done

**Comment by thisisthekap** [comment]
I moved the theme definition from a class annotation to a xml attribute of AndroidManifest. Worked for me. Seems like a bug of Zendesk when reading the theme.
