### ISSUE TITLE
Error building for ios

### ISSUE THREAD

**Issue by reimo** [MrHou/zdplugin#2]
### This worked ok for android but we are having this error while building the app for IOS 

Running Xcode build...                                                  
Xcode build done.                                           14.1s
Failed to build iOS app
Error output from Xcode build:
↳
    * BUILD FAILED *

Xcode's output:
↳
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:3:8: error: error extracting
    version from module interface
    import SupportSDK
           ^
    /Users/imo/web/reimnet/clients/suez/suezElectric/ios/Pods/ZendeskSupportSDK/SupportSD
    K.framework/Modules/SupportSDK.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:
    1:1: error: error extracting version from module interface
    // swift-interface-format-version: 1.0
    ^
    /Users/imo/web/reimnet/clients/suez/suezElectric/ios/Pods/ZendeskSupportProvidersSDK/
    SupportProvidersSDK.framework/Modules/SupportProvidersSDK.swiftmodule/x86_64-apple-io
    s-simulator.swiftinterface:1:1: error: error extracting version from module interface
    // swift-interface-format-version: 1.0
    ^
    /Users/imo/web/reimnet/clients/suez/suezElectric/ios/Pods/ZendeskSupportProvidersSDK/
    SupportProvidersSDK.framework/Modules/SupportProvidersSDK.swiftmodule/x86_64-apple-io
    s-simulator.swiftinterface:1:1: error: error extracting version from module interface
    // swift-interface-format-version: 1.0
    ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:4:8: error: error extracting
    version from module interface
    import ChatSDK
           ^
    /Users/imo/web/reimnet/clients/suez/suezElectric/ios/Pods/ZendeskChatSDK/ChatSDK.fram
    ework/Modules/ChatSDK.swiftmodule/x86_64-apple-ios-simulator.swiftinterface:1:1:
    error: error extracting version from module interface
    // swift-interface-format-version: 1.0
    ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:5:8: error: error extracting
    version from module interface
    import ChatProvidersSDK
           ^
    /Users/imo/web/reimnet/clients/suez/suezElectric/ios/Pods/ZendeskChatProvidersSDK/Cha
    tProvidersSDK.framework/Modules/ChatProvidersSDK.swiftmodule/x86_64-apple-ios-simulat
    or.swiftinterface:1:1: error: error extracting version from module interface
    // swift-interface-format-version: 1.0
    ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:6:8: error: error extracting
    version from module interface
    import ZendeskCoreSDK
           ^
    /Users/imo/web/reimnet/clients/suez/suezElectric/ios/Pods/ZendeskCoreSDK/ZendeskCoreS
    DK.framework/Modules/ZendeskCoreSDK.swiftmodule/x86_64-apple-ios-simulator.swiftinter
    face:1:1: error: error extracting version from module interface
    // swift-interface-format-version: 1.0
    ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:8:8: error: error extracting
    version from module interface
    import MessagingSDK
           ^
    /Users/imo/web/reimnet/clients/suez/suezElectric/ios/Pods/ZendeskMessagingSDK/Messagi
    ngSDK.framework/Modules/MessagingSDK.swiftmodule/x86_64-apple-ios-simulator.swiftinte
    rface:1:1: error: error extracting version from module interface
    // swift-interface-format-version: 1.0
    ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:23:13: error: 'Logger' is
    unavailable: cannot find Swift declaration for this class
                Logger.isEnabled = true
                ^~~~
    ChatProvidersSDK.Logger:2:14: note: 'Logger' has been explicitly marked unavailable
    here
    public class Logger : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:24:13: error: 'Logger' is
    unavailable: cannot find Swift declaration for this class
                Logger.defaultLevel = .verbose
                ^~~~
    ChatProvidersSDK.Logger:2:14: note: 'Logger' has been explicitly marked unavailable
    here
    public class Logger : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:38:13: error: 'Zendesk' is
    unavailable: cannot find Swift declaration for this class
                Zendesk.initialize(appId: applicationId,
                ^~~
    ZendeskCoreSDK.Zendesk:2:14: note: 'Zendesk' has been explicitly marked unavailable
    here
    public class Zendesk : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:41:13: error: 'Support' is
    unavailable: cannot find Swift declaration for this class
                Support.initialize(withZendesk: Zendesk.instance)
                ^~~
    SupportProvidersSDK.Support:2:14: note: 'Support' has been explicitly marked
    unavailable here
    public class Support : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:42:43: error: cannot find
    'Identity' in scope
                Zendesk.instance?.setIdentity(Identity.createAnonymous(name:nameIdentifie
                r, email: emailIdentifier))
                                              ^~~~
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:42:13: error: 'Zendesk' is
    unavailable: cannot find Swift declaration for this class
                Zendesk.instance?.setIdentity(Identity.createAnonymous(name:nameIdentifie
                r, email: emailIdentifier))
                ^~~
    ZendeskCoreSDK.Zendesk:2:14: note: 'Zendesk' has been explicitly marked unavailable
    here
    public class Zendesk : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:53:13: error: 'Chat' is
    unavailable: cannot find Swift declaration for this class
                Chat.initialize(accountKey: accountKey,appId:applicationId)
                ^~
    ChatProvidersSDK.Chat:2:14: note: 'Chat' has been explicitly marked unavailable here
    public class Chat : NSObject {
                 ^
    /Users/imo/web/reimnet/clients/suez/suezElectric/ios/Pods/ZendeskSDKConfigurationsSDK
    /SDKConfigurations.framework/Modules/SDKConfigurations.swiftmodule/x86_64-apple-ios-s
    imulator.swiftinterface:1:1: error: error extracting version from module interface
    // swift-interface-format-version: 1.0
    ^
    /Users/imo/web/reimnet/clients/suez/suezElectric/ios/Pods/ZendeskSDKConfigurationsSDK
    /SDKConfigurations.framework/Modules/SDKConfigurations.swiftmodule/x86_64-apple-ios-s
    imulator.swiftinterface:1:1: error: error extracting version from module interface
    // swift-interface-format-version: 1.0
    ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:70:28: error:
    'HelpCenterUiConfiguration' is unavailable: cannot find Swift declaration for this
    class
                let hcConfig = HelpCenterUiConfiguration()
                               ^~~~~~~~~
    SupportSDK.HelpCenterUiConfiguration:2:14: note: 'HelpCenterUiConfiguration' has been
    explicitly marked unavailable here
    public class HelpCenterUiConfiguration : NSObject, Configuration {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:72:30: error: cannot find
    'HelpCenterUi' in scope
                let helpCenter = HelpCenterUi.buildHelpCenterOverviewUi(withConfigs:
                [hcConfig])
                                 ^~~~~~
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:77:34: error: 'RequestUi' is
    unavailable: cannot find Swift declaration for this class
                let viewController = RequestUi.buildRequestUi(with: [])
                                     ^~~~~
    SupportSDK.RequestUi:2:14: note: 'RequestUi' has been explicitly marked unavailable
    here
    public class RequestUi : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:81:34: error: 'RequestUi' is
    unavailable: cannot find Swift declaration for this class
                let viewController = RequestUi.buildRequestList(with: [])
                                     ^~~~~
    SupportSDK.RequestUi:2:14: note: 'RequestUi' has been explicitly marked unavailable
    here
    public class RequestUi : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:112:9: error: 'Chat' is
    unavailable: cannot find Swift declaration for this class
            Chat.profileProvider?.addTags(["标签：昵称："+name+" 手机号："+phone])
    ChatProvidersSDK.Chat:2:14: note: 'Chat' has been explicitly marked unavailable here
    public class Chat : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:114:45: error:
    'ChatFormConfiguration' is unavailable: cannot find Swift declaration for this class
            let chatFormConfiguration = ChatSDK.ChatFormConfiguration.init(name:
            .required, email: .hidden, phoneNumber: .hidden, department: .hidden)
                                                ^~~~~~~~~
    ChatSDK.ChatFormConfiguration:2:14: note: 'ChatFormConfiguration' has been explicitly
    marked unavailable here
    public class ChatFormConfiguration : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:116:33: error:
    'ChatConfiguration' is unavailable: cannot find Swift declaration for this class
            let chatConfiguration = ChatConfiguration()
                                    ^~~~~~~
    ChatSDK.ChatConfiguration:2:14: note: 'ChatConfiguration' has been explicitly marked
    unavailable here
    public class ChatConfiguration : NSObject, Configuration {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:129:38: error:
    'MessagingConfiguration' is unavailable: cannot find Swift declaration for this class
            let messagingConfiguration = MessagingConfiguration()
                                         ^~~~~~~~
    MessagingSDK.MessagingConfiguration:2:14: note: 'MessagingConfiguration' has been
    explicitly marked unavailable here
    public class MessagingConfiguration : NSObject, Configuration {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:132:30: error: 'ChatEngine' is
    unavailable: cannot find Swift declaration for this class
            let chatEngine = try ChatEngine.engine()
                                 ^~~~
    ChatSDK.ChatEngine:2:14: note: 'ChatEngine' has been explicitly marked unavailable
    here
    public class ChatEngine : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:134:34: error: 'Messaging' is
    unavailable: cannot find Swift declaration for this class
            let viewController = try Messaging.instance.buildUI(engines: [chatEngine],
            configs: [chatConfiguration,messagingConfiguration])
                                     ^~~~~
    MessagingSDK.Messaging:2:14: note: 'Messaging' has been explicitly marked unavailable
    here
    public class Messaging : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:139:40: error:
    'ChatAPIConfiguration' is unavailable: cannot find Swift declaration for this class
                let chatAPIConfiguration = ChatAPIConfiguration()
                                           ^~~~~~~~
    ChatProvidersSDK.ChatAPIConfiguration:2:14: note: 'ChatAPIConfiguration' has been
    explicitly marked unavailable here
    public class ChatAPIConfiguration : NSObject {
                 ^
    /Users/imo/development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_zendes_plug
    in-1.0.3/ios/Classes/SwiftFlutterZendeskPlugin.swift:141:13: error: 'Chat' is
    unavailable: cannot find Swift declaration for this class
                Chat.instance?.configuration = chatAPIConfiguration
                ^~
    ChatProvidersSDK.Chat:2:14: note: 'Chat' has been explicitly marked unavailable here
    public class Chat : NSObject {
                 ^
    note: Using new build system
    note: Building targets in parallel
    note: Planning build
    note: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 11 Pro.

**Comment by harleyGit** [comment]
note: Using new build system

please using new build system,
in Xcode, plese selecet File -> Workspace Settings.. -> Build System , choose  "New Build System(Ddfault)"
